name: todo_mvvm
description: "A Todo App using MVVM architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.2
  provider: ^6.1.2

  cupertino_icons: ^1.0.8
  floor: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2



flutter:

  uses-material-design: true
